services:
    panel:
        image: ghcr.io/stegripe/swas-panel:latest-dev
        container_name: swas-panel
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:11.7
        container_name: swas-mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - db_data:/var/lib/mysql
            - ./mariadb-my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "3306:3306"

volumes:
    db_data:
