name: Build and Push Docker Image to the container image registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: stegripe/workflows/.github/workflows/docker-build-and-push-multiarch.yaml@564a369e6527436f62073f0f1a0ea6626596c6a9 # main
    secrets: inherit
